### ISSUE TITLE
Cache activity validation status

### ISSUE THREAD

**Issue by mattdailis** [NASA-AMMOS/aerie#1195]
Backend implementation ticket for https://github.com/NASA-AMMOS/aerie-ui/issues/281

To implement the desired design, the backend will need to populate a table with the pre-computed results of an activity validation for a given activity directive revision.

There are two main chunks of work to implement this:
- [ ] Create a `jsonb` column in either `activity_directive_validation` or `activity_directive_changelog`, and populate it with the JSON that is returned from `ResponseSerializers.serializeValidationNotices`. This cached validation should be tied to an `activity_directive`'s revision, which is mostly tracked in `activity_directive_changelog`.
- [ ] Figure out some automation (database triggers) to run validation and cache results for every updated / inserted activity.

**Comment by skovati** [comment]
Current proposed design:

![Image](https://github.com/NASA-AMMOS/aerie/assets/49844593/6f2055f7-20c5-4850-ab0f-f30a890aa801)

**Comment by dandelany** [comment]
Per @skovati the main functionality of this has been implemented in a branch, but there are some improvements still to be made which may impact performance. @skovati will submit a draft PR in the next week or two for review.

**Comment by skovati** [comment]
Significantly changed design direction, warranting the new PR.

Design changes are as follows:
 - Move validation thread into `merlin-server` since this first iteration has no support for multiple validation threads efficiently sharing work. It should be trivial to move this thread around to different containers in the future if desired.
 - Reduce number of validation calls by only requesting validation if directive arguments changed. This is achieved by a `before update on arguments` DB trigger that inserts a new validation request into `activity_directive_validations`.
 - Switch from a push based model using Postgres signals to a pull based model, which runs a query to get unvalidated directives every e.g. 500ms

![caching_design(1)](https://github.com/NASA-AMMOS/aerie/assets/49844593/0808e753-9c80-47bc-a3b0-31408b634217)
