### ISSUE TITLE
Improve the User Experience with the API Playground

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie#1210]
Currently, our API Playground is very rough to use, as by default there is no way for the user to view our Schema, and they have to log in to the Gateway to get the token in order to set the Authorization header.

This issue is for addressing these pain points to make the Playground a better replacement for the Hasura Console for non-admin users.

**Comment by parkerabercrombie** [comment]
This would be very useful for Clipper (and I imagine other missions). The Hasura console is very useful, but because it gives direct database access we can't share it with users on production venues. It would be really useful to have an API playground that worked smoothly with Aerie and provided the GraphQL schema in a useful format.

**Comment by dandelany** [comment]
These improvements are largely done by @Mythicaeda in branch `improve-altair-experience` branch - the only remaining portion is some questions about authentication - @Mythicaeda will meet with @duranb to discuss.

**Comment by mattdailis** [comment]
Needs estimation - consider splitting into two
