### ISSUE TITLE
Migrate backend services and release automation to node 20 LTS version

### ISSUE THREAD

**Issue by joswig** [NASA-AMMOS/aerie#1228]
Currently our release automation fails with node 20

We've pinned the release to node 18 in the interim, and we can move forward to 20, 22, etc once the build issue is corrected

**Comment by joswig** [comment]
Looks like this ts-node bug is part of the problem https://github.com/TypeStrong/ts-node/issues/2094

**Comment by dyst5422** [comment]
I'll add that a switch to using [`tsx`](https://www.npmjs.com/package/tsx) as a node loader rather than ts-node should be considered as well. (It's been suggested in the thread @joswig linked above a number of times).

Anecdotally, I've been using tsx for all my projects the last ~year+ with great success.

**Comment by dandelany** [comment]
For reference, the release automation workflow upgrades may be similar to these changes made for our workflow on the aerie repo: https://github.com/NASA-AMMOS/aerie/pull/1339
