### ISSUE TITLE
State of resumable simulation driver is not properly maintained

### ISSUE THREAD

**Issue by jmdelfa** [NASA-AMMOS/aerie#1256]
### Checked for duplicates

No - I haven't checked

### Is this a regression?

No - This is a new bug

### Version

develop

### Describe the bug

State of resumable simulation driver is not properly maintained. 
plannedDirectiveToTask is not updated with activities that have an anchor, therefore simulation is finishing early

### Reproduction

N/A

### Logs

```shell
N/A
```

### System Info

```shell
N/A
```

### Severity

Moderate

**Comment by adrienmaillard** [comment]
The current stopping condition in `ResumableSimulationDriver` is not effective in certain cases: 
```
if (!plannedDirectiveToTask.isEmpty() && plannedDirectiveToTask
          .values()
          .stream()
          .allMatch(engine::isTaskComplete)) {
        allTaskFinished = true;
      } 
```
Let A1 and A2 be 2 non-concurrent activities, with A2 anchored to the end of A1. The state of A1 will not be complete until A2 has been finished, defeating the purpose of this condition (stopping the simulation at the end of a task).

**Comment by adrienmaillard** [comment]
The bug witnessed is of a different form: with A1 and A2 defined as above, the driver was stopping at the end of A1 because A2's `TaskId` is not put in `plannedDirectiveToTask` at the beginning of simulation but spawned by the fake parent of A1 and A2. When checking if all the items `plannedDirectiveToTask` are finished, it finds that A1 is finished and finishes simulation. Obviously, this contradicts what is being observed in my comment just above. More inquiry is required.
