### ISSUE TITLE
Spice Fails to Load on M1 Macs during Simulation

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie#541]
## Summary:
When attempting to simulate a plan whose model loads SPICE, the following error occurs when SPICE is loaded:

```
java.lang.UnsatisfiedLinkError: /tmp/JNISpice-4439314142500713632.tmp: /tmp/JNISpice-4439314142500713632.tmp: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64 .so on a AARCH64 platform)
```

@Twisol and I have so far been discussing this in PR #322.

## How to Reproduce:
1) Build the Banananation model found on the `fix/spice_m1` branch
2) Compose up Aerie into Docker
3) Via the UI, upload the Banananation Model and create a new Plan from the model
4) Via the UI, attempt to simulate the new Plan

**Comment by Twisol** [comment]
So far, we've determined that this issue does *not* occur (i.e. SPICE loads successfully) when running the model directly from IntelliJ. This issue only manifests when loading SPICE in a Docker environment on an M1 host.

[My working hypothesis](https://github.com/NASA-AMMOS/aerie/pull/322#issuecomment-1353550129) is that, since the Docker environment identifies as Linux, the `SpiceLoader` will use the bundled `.so`, which only works on x86_64 and not on ARM M1. In contrast, when run directly within MacOS, the `SpiceLoader` will use the bundled `.jnilib`, which includes slices for both architectures.

NAIF [does not provide](https://naif.jpl.nasa.gov/naif/toolkit_C.html) Linux+ARM builds of SPICE; only Linux+Intel. They provide both ARM and Intel builds for MacOS, and it is those that were fused into the bundled `.jnilib` for MacOS.

Without a way to build SPICE for Linux on ARM chipsets, I think we will not be able to address this issue at its heart. @Mythicaeda, your best bet may be to use a Docker image built for Intel architectures rather than ARM architectures -- Rosetta will take care of emulation, and then the contained Linux OS will be able to use the NAIF-supported `.so`.

**Comment by Mythicaeda** [comment]
> My working hypothesis is that, since the Docker environment identifies as Linux, the SpiceLoader will use the bundled .so, which only works on x86_64 and not on ARM M1.

Based on the following Postgres log line, I think you're correct that the Docker environment considers itself to be Linux:

```
LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
```

<details>
  <summary>For further confirmation, I ran this code block inside of `aerie_merlin_worker` (which was the container throwing the error), and it returned that its OS is `Linux`</summary>

```java
public class OSType{
  public static void main(String[] args){
    System.out.println(System.getProperty("os.name"));
  }
}
```
</details>

<details>
<summary>This means that, based on `SpiceLoader.getResourcePathByOS()`, it's definitly attempting to load the `.so` rather than the `.jnilib`</summary>

```java
private static String getResourcePathByOS() {
        final String osName = System.getProperty("os.name").toLowerCase();

        if (osName.startsWith("win")) {
            return "JNISpice.dll";
        } else if (osName.startsWith("linux")) {
            return "libJNISpice.so";
        } else if (osName.startsWith("mac")) {
            return "libJNISpice.jnilib";
        }

        throw new UnsupportedOperationException("Platform " + osName + " is not supported by JNISpice.");
    }
```
</details>

> Without a way to build SPICE for Linux on ARM chipsets, I think we will not be able to address this issue at its heart. @Mythicaeda, your best bet may be to use a Docker image built for Intel architectures rather than ARM architectures -- Rosetta will take care of emulation, and then the contained Linux OS will be able to use the NAIF-supported .so.

I think you're right, which is a shame since I started looking into this because I had heard about some performance/stability issues with running the Intel-architecture images on M1 machines. I'm not sure how frequently/debilitating these are off the top of my head, but it sucks regardless that they can't be mitigated by publishing or having the user build M1 images.

On a related note, we ought to document this situation with Docker, NAIF and the `.so`. I'm tempted to suggest the original PR just to have all the notes regarding it in one place (even though it took us several months to discover this side effect), although if you have a better idea, I'd be open to hearing it.

**Comment by Mythicaeda** [comment]
@Twisol, it doesn't look like the Linux build for SPICE is Intel specific, it just specifies use of the GCC compiler, which [appears to have ARM support](https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html). Should we be able to get the Linux+ARM `.so`, would we be able to use `lipo` to combine them like you did with the `.jnilib`s or would we need a different tool?

**Comment by Twisol** [comment]
I think `lipo` is a MacOS-specific tool, and moreover I'm not sure if Linux has an analogous concept to MacOS' "universal executable", which is how `lipo` is able to package two libraries into one file in the first place.

Assuming we can get a Linux+ARM build, I think we could tweak `SpiceLoader` to pick between ARM and Intel binaries by querying the `os.arch` system property (see [here](https://stackoverflow.com/questions/63296556/i-programmatically-determine-operating-system-in-java)).

**Comment by Mythicaeda** [comment]
Ah, so even if we were to use `lipo` to combine them (and it _seems_ like the tool doesn't care about OS, just about the architecture, so we ought to be able to combine them if we had both files on a Mac), it won't be understood when its run?

In that case, then I agree on filtering based on `os.arch`. It looks like the filters would be `aarch64`, `arm64`, `amd`, and `x_86`, with `aarch` and `arm` pointing at the new `.so` and `amd` and `x_86` pointing at the old one, correct?

**Comment by Twisol** [comment]
> Ah, so even if we were to use `lipo` to combine them (and it _seems_ like the tool doesn't care about OS, just about the architecture, so we ought to be able to combine them if we had both files on a Mac), it won't be understood when its run?

I'm not clear on all the details, but for instance, binaries on Linux tend to be in ELF format, while binaries on MacOS tend to be in Mach-O format. It's less about the instructions themselves and more about the container formats they're being carried in. I'm not confident that the format used by Linux binaries would be understood by `lipo` running on MacOS; it's not clear to me where the "universal executable" concept leveraged by `lipo` exists in the format stack, and whether that's something that can even be done with Linux binaries.

**Comment by Twisol** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/Executable_and_Linkable_Format) and [this Quora answer](https://qr.ae/prNkew) suggest that ELF does not support this concept of a universal binary in the first place.

**Comment by Mythicaeda** [comment]
When making the `.jnispice` in your original PR, how did you remove the `-flat_namespace` flag? Is there one specific spot or did you have to go through each directory's build script and modify it there? The Linux version has a flag to force it to build as 64-bit on Intel that I need to remove. Additionally, did you need to perform any additional steps to get the `.jnilib` or was that output from running the `makeall.csh`?

**Comment by Twisol** [comment]
I *think* you only need to do it in the `Makefile` for the JNISpice component, but I'm not 100% sure. If I recall correctly, I ended up tweaking it in all of the build scripts, then realized I probably didn't need to.



> Additionally, did you need to perform any additional steps to get the `.jnilib` or was that output from running the `makeall.csh`?

I ran `make` specifically from within the JNISpice component, I think. You might need to run `makeall.csh` at least once to get all the dependencies built, so it might be worth just making the build changes and running `makeall.csh`. If that doesn't build JNISpice too, just build it separately.

It was kind of an involved and exploratory process; I didn't write down my findings because it was kind of a circuitous path to get there. I wish NAIF provided support for these platforms directly 😓

**Comment by Mythicaeda** [comment]
Oh does the Mac version provide a Makefile? I ended up setting environment variables so I didn't have to go through each `mkprodct.csh`. 

Thanks for the tip about rebuilding JNISpice-- the `makeall.csh` doesn't recompile/rebuild that directory.

And I know what you mean about it being circuitous, I documented what I did, but I'm going to have to repeat the process to get the correct set of instructions, because I kept trying slight modifications to ""fix"" the `.so` when the actual issue at some point became that I forgot to recompile the mission model (so it was still using the Intel `.so` 🤦‍♀️).
