### ISSUE TITLE
Add search feature to help documentation

### ISSUE THREAD

**Issue by lklyne** [NASA-AMMOS/aerie#558]
As far as I can tell there's no ability to search the aerie documentation website. There's a lot of information in there and as a newcomer it's hard to know where to find things. 

https://nasa-ammos.github.io/aerie/stable/

**Comment by Mythicaeda** [comment]
Two quick starting points: 

1. The [Docasaurus Docs](https://docusaurus.io/docs/search) mention several search options. Biggest concern with those options would just be compatibility with Sphinx, since Docasaurus uses JS rather than our current Python pipeline, although I know that Scylla (our docs theme provider) was using a paid third party script for their searches and I believe they were loading it via a [`CustomScripts.html` file](https://github.com/scylladb/sphinx-scylladb-theme/blob/6f70bccfe6e52b6ebbf8e80d9b27d6f8c308f6c3/sphinx_scylladb_theme/custom-scripts.html).
2. [SphinxSearch](http://sphinxsearch.com/docs/current.html) or maybe something similar

**Comment by camargo** [comment]
I'm doing some prototyping of moving our docs to [Docusaurus](https://docusaurus.io/) here: https://nasa-ammos.github.io/aerie-docs
It uses https://www.algolia.com/ and is supported pretty much out of the box which is nice. I'll play with configuring it more next week.

**Comment by camargo** [comment]
Completed in https://github.com/NASA-AMMOS/aerie-docs/commit/0b7a6e145f129ec9c9a84ecd8764d80598a57afc
