### ISSUE TITLE
Improve performance of big data nested relationship queries

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#574]
Say we have the following query. It gets a plan, simulation, simulation_dataset, dataset, profiles, and profile_segments, all via joins (created with Hasura relationships):

```gql
query GetSimulationDataset($planId: Int!) {
  plan_by_pk(id: $planId) {
    simulations(order_by: { id: desc }, limit: 1) {
      simulation_datasets(order_by: { id: desc }, limit: 1) {
        dataset {
          profiles {
            name
            profile_segments(order_by: { start_offset: asc }) {
              dynamics
              start_offset
            }
            type
          }
        }
        id
        reason
    }
    start_time
  }
}
```

We have observed on an Aerie instance with 2+ million profile segments that this query crawls and never completes (waited 10+ minutes and it never completed). This ticket is to investigate and come up with ways we can improve performance of this query. The workaround is to just do separate queries for now.

**Comment by dyst5422** [comment]
So we've finally come to the point of SQL biting us. How fun.

**Comment by camargo** [comment]
Upon further investigation just a single relationship from profile to profile_segments causes the query never complete (with 2+ million segments):

```gql
query GetProfiles($datasetId: Int!) {
  profile(where: { dataset_id: { _eq: $datasetId } }) {
    name
    profile_segments {
      profile_id
      dynamics
      start_offset
    }
  }
}
```

**Comment by camargo** [comment]
Here is a workaround query that queries for the dataset and profile segments separately (but in the same query). This query uses no relationships and completes almost instantly with 2+ million segments:

```gql
query GetDatasetAndProfileSegments($datasetId: Int!) {
  dataset_by_pk(id: $datasetId) {
    id
    profiles {
      id
      name
      type
    }
  }
  profile_segment(where: { dataset_id: { _eq: $datasetId } }) {
    dynamics
    profile_id
    start_offset
  }
}
```

**Comment by Twisol** [comment]
Interesting. I'd like to poke at this a little independently -- do you have any database seed scripts to help get up to the sizes necessary to observe this problem?

**Comment by camargo** [comment]
@Twisol That would be amazing. We do not have seed data for this one unfortunately. This was observed on a long-running Clipper instance of Aerie.

**Comment by Twisol** [comment]
Hmm, okay. This is my first time spinning up the Docker stack since I was at JPL, so if you need to get to this with any haste, don't worry about picking this back off of me.

**Comment by Twisol** [comment]
The first thing I want to try is to run the slow query with `EXPLAIN (ANALYZE, BUFFERS)` (see [here](https://www.cybertec-postgresql.com/en/how-to-interpret-postgresql-explain-analyze-output/)) and post the output so we can get some idea of what bottlenecks Postgres is hitting. The Hasura web front-end has a way of getting the SQL generated for a given GraphQL query; I'd recommend cutting Hasura out of the problem scope ASAP.

If someone else can get to that faster, by all means :+1:

**Comment by Twisol** [comment]
> Upon further investigation just a single relationship from profile to profile_segments causes the query never complete (with 2+ million segments):

Can you confirm where the 2+ million segments number comes from? Is this 2+ million segments associated with one profile; 2+ million segments in a single dataset-associated partition (but spread over multiple profiles); or 2+ million segments over the whole profile_segment table?

**Comment by camargo** [comment]
In this example there are 2+ million segments over the whole profile_segment table (2,558,7873 to be precise). 
There are only 6099 profile segments in the single dataset-associated partition spread over multiple profiles. 

Counting query used for reference:

```gql
query GetProfileSegmentsCount($datasetId: Int!) {
  profile_segment_aggregate(where: { dataset_id: { _eq: $datasetId } }) {
    aggregate {
      count
    }
  }
}
```

**Comment by Twisol** [comment]
How many partitions of `profile_segment` are there? 🤔 You might have to drop to SQL specifically for that one.

**Comment by camargo** [comment]
I don't have direct access to the database on this instance. But just looking in Hasura there are ~72 untracked "profile_segment_X" "tables", where each one is a partition I believe?

**Comment by Twisol** [comment]
I haven't actually gotten things going yet, but I have a hunch I'd like to share.

`profile.sql` currently declares this relationship:
```sql
  constraint profile_segment_owned_by_profile
    foreign key (profile_id)
    references profile
    on update cascade
    on delete cascade
```

However, `profile_id` is not sufficient alone to identify the partition (which is defined on `dataset_id`), meaning that a relationship query from `profile` to `profile_segment` likely is not including sufficient information for Postgres to avoid a scan of every partition. This would also line up with Emily's observation that the time a query takes appears to grow with repeated simulations -- every simulation gets a new partition.

I'd like to suggest replacing this with a composite foreign key:

```sql
  constraint profile_segment_owned_by_profile
    foreign key (dataset_id, profile_id)
    references profile
    on update cascade
    on delete cascade
```

However, this foreign key requires that `(dataset_id, profile_id)` itself be at least UNIQUE in `profile`. While `profile` does declare `PRIMARY KEY (id)` (which implies UNIQUE), it only declares `UNIQUE (dataset_id, name)`, so the required tuple `(dataset_id, id)` is not actually a key.

We can fix this by either adding a new `UNIQUE` constraint to `profile`, or altering the existing `PRIMARY KEY` to include `dataset_id`. I think I prefer the former, since altering the `PRIMARY KEY` would likely have impacts on the Hasura-generated API, but I've gone back and forth on this a little.

```sql
  constraint profile_partition_key
    unique (dataset_id, id)
```

Ideally, this should be easy enough to test with a migration. I'll keep poking at my local setup.

**Comment by dyst5422** [comment]
@Twisol What is the effect of https://github.com/NASA-AMMOS/aerie/blob/develop/merlin-server/sql/merlin/tables/profile_segment.sql#L17 on the behavior of the profile_segment relationship to profile?

**Comment by Twisol** [comment]
> @Twisol What is the effect of https://github.com/NASA-AMMOS/aerie/blob/develop/merlin-server/sql/merlin/tables/profile_segment.sql#L17 on the behavior of the profile_segment relationship to profile?

Within Postgres, `profile_segment` is actually split into many tables based on the criterion given (here, the value of the `dataset_id` column). This makes queries involving equality comparisons on that column much faster, because any given value excludes all but at most one table.

However, queries on `profile_segment` that don't involve that column effectively have to replicate the query across every one of the partitions, since it can't know which tables the required data exist in.

For our use case, essentially all queries on profile segments are in-scope of a single specified dataset, so this is a good tradeoff. However, depending on the SQL generated by Hasura (which I'm not yet able to see; it's something you can extract by hitting a button in the Hasura frontend GraphQL playground), the problematic query in this issue is likely to be using subqueries for each visited relationship; and if the subquery for the segments doesn't itself reference `dataset_id`, but rather just `profile_id`, then Postgres doesn't actually know which table to find the profile in.

Hasura generates SQL for a query based on the foreign key relationships in the database. Based on my imagined Hasura-generated SQL, if we augment the foreign key to require the owning `dataset_id`, we can force Hasura to include it in the subquery, thereby giving Postgres the information it needs to select the single table of interest.

**Comment by Twisol** [comment]
Assuming all this theorycrafting is correct, an alternative might be to add an index on `profile_segment` for the `profile_id` column. However, because of the sheer quantity of segments that we can get per simulation, I'm really, really hesitant to add an index upkeep step to every insert on this table -- that cure might end up worse than the disease.

**Comment by mattdailis** [comment]
Well - I'm late to the party! I've been independently poking around at things related to #588 and arrived at some information related to this issue. @Twisol I think your hunch is spot on - the query is indeed doing a sequential scan of all the partitions. I ran EXPLAIN ANALYZE and put it into a visualizer:

https://explain.dalibo.com/plan/961f610314d9e291

You can find the SQL for the query in the "Query" tab on that webpage

**Comment by Twisol** [comment]
Oh sweet, thanks for looking into this! (Winter quarter just started and I am incredibly behind on preparing a poster+slides for a conference I'm attending X_x)

**Comment by Twisol** [comment]
That `APPEND` node near the bottom seems to be where things go awry -- it runs a sequential scan over every partition, then concatenates them into a single result set. The scan itself isn't necessarily a problem (especially if we're asking for all profile segments for a dataset -- we need every row anyway!) -- it's the fact that we're hitting every partition with a sequential scan. We only need to hit one partition (the last one!); all the other sequential scans are entirely wasted work, because we shouldn't be querying the other partitions to begin with.
