### ISSUE TITLE
Add better way to upload large external datasets

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#593]
Currently Clipper is uploading large external datasets and using the API to do this is a pain. We need to come up with a better way. This could include adding files to the Aerie file system directly, or some kind of streaming file input solution.

Related to https://github.com/NASA-AMMOS/aerie/issues/515

**Comment by mattdailis** [comment]
@camargo @parkerabercrombie I'm taking a crack at this one now. It seems like adding an `extendExternalDataset` action is the most straightforward option, so I'm starting there. This will at least make it possible to upload large datasets - if perhaps not in the most efficient way.

**Comment by camargo** [comment]
So just to be clear `extendExternalDataset` would allow uploading the dataset in chunks?

**Comment by mattdailis** [comment]
> So just to be clear `extendExternalDataset` would allow uploading the dataset in chunks?

Yes, exactly.

Notionally I'm imagining keeping the same shape as `addExternalDataset`, with the following differences:
- Instead of a plan id, provide a dataset id
- Do not provide the dataset start time - that would be assumed to be the same as the original dataset

As I'm working through it now, I'm leaving the possibility open to add wholly new profiles as part of `extendExternalDataset` (so, if the profile exists, add the segments to the end - if it doesn't, make a new profile). If that feels like a foot-gun I can restrict `extendExternalDataset` to only allow appending segments to existing profiles.

**Comment by parkerabercrombie** [comment]
Thanks for the effort on this. I was able to get a more realistic dataset from the GNC team. Unfortunately it's a 2.7 GB file for a six week plan. We did some back-of-the-envelope math and found that we can only upload about 60 data points at a time before we hit the hasura payload size limitation, which would mean we we'd need more than 32,000 requests to upload the full file 😬 . I'm asking the GNC folks if this is really what they need to see in Aerie. Hopefully we can do something on the data production side, because I don't think the `extendExternalDataset` solution will scale to this data size.

**Comment by camargo** [comment]
@parkerabercrombie In the worst case if all of that data is needed, we could try cranking up the max request size in Merlin as proposed in https://github.com/NASA-AMMOS/aerie/issues/515 so fewer requests are needed. I am assuming that is the data limit you are hitting? Or is there another one in Hasura?

**Comment by parkerabercrombie** [comment]
I think it's just the limitation mentioned in #515 (I was mis-remembering when I said hasura).

**Comment by mattdailis** [comment]
Unfortunately, it does not look like there's a good way to do client-side compression of mutations (the [hasura docs](https://hasura.io/docs/latest/deployment/compression/) only mention compression of responses, and [this issue](https://github.com/hasura/graphql-engine/issues/5324) confirms that). 

I'll continue to ponder....
