### ISSUE TITLE
Associate external datasets with a simulation dataset instead of a plan

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#594]
Clipper is using external datasets with simulation datasets instead of plans. We should update our data model to reflect this association.

**Comment by Twisol** [comment]
Should we associate external datasets with a simulation dataset, or with the originating simulation description? Surely they want to be able to rerun a simulation (and thus generate a new simulation dataset) whilst holding their external datasets constant?

Also, I'm curious what obstacles customers have faced with plan-associated datasets that leads us to understand a change to the data model?

**Comment by camargo** [comment]
The use case they are describing is they create a new external dataset at the end of every simulation run so they need a way to make that association (from simulation dataset to external dataset).

**Comment by Twisol** [comment]
Okay, that makes sense. Aren't there also other kinds of datasets that are uploaded once and then reused across runs and between multiple simulation configurations? There were existing use-cases that drove the current design. Does this imply we need a more flexible way to describe associations at various levels?

**Comment by Twisol** [comment]
What process does the proposed dataset-level association drive? Is this metadata that's only read and written by downstream clients, or will it feed into downstream functionality provided by Aerie?

**Comment by parkerabercrombie** [comment]
In our use case, we have several external tools which do post-processing of the simulation results (e.g. more advanced modeling for some subsystems). These tools push timelines back to Aerie so that constraints can be checked on the external data. Because these timelines need to be recomputed for each simulation it doesn't work for the external data to be linked to the plan. If a new sim starts we want to keep the old external dataset results (in case it was an important run-for-record simulation), but not display those results with the new simulation. It is extremely important that we do not display stale external datasets with new sim data, that would kill use confidence in the system since the external data is supposed to be the more accurate model.

We do have other cases where we precompute timelines, but we do not use external timelines for those cases because the external timelines are not accessible during simulation. The only reason we precompute is to save time during the simulation, so the mission model needs access to those timelines as the sim runs.

**Comment by parkerabercrombie** [comment]
@camargo any updates on when we might expect this fix?

**Comment by camargo** [comment]
@mattdailis is actively working on this and - as of his status update yesterday - expects to push something up soon. Stay tuned.
