### ISSUE TITLE
Postgres container unresponsive: remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by parkerabercrombie** [NASA-AMMOS/aerie#631]
We got into a situation where postgres became completely unresponsive for about 10 min. During this time the UI would not load any models, plans, etc, and CPU usage on the Postgres container was pegged at 100%. After about 10 min CPU dropped and the service became responsive again. Around this time I was trying to delete some plans, and experience very long query times. Don't know if that was a cause of the CPU spike or not. Postgres log attached.

[postgres.log.txt](https://github.com/NASA-AMMOS/aerie/files/10551705/postgres.log.txt)

**Comment by cartermak** [comment]
Adding that I'm experiencing the same behavior on another host, potentially related to the fact that I'd just tried twice to delete a (blank, 2-day) plan. 

Postgres resource usage:

```
CONTAINER ID   NAME       CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O        PIDS
c01040bd6bf3   postgres   101.28%   4.119GiB / 62.62GiB   6.58%     7.38GB / 30GB   125MB / 13.5GB   104
```

Very similar-looking Postgres logs:
[postgres_logs.txt](https://github.com/NASA-AMMOS/aerie/files/10700739/postgres_logs.txt)

**Comment by Mythicaeda** [comment]
Managed to repro while testing an update to `aerie_db_migration`. Currently trying to see if it can be consistently reproduced. 

The output from `aerie_db_migration_output.txt` was the output where I:
1. Ran a mass-revert after Postgres was ready for connections but before Hasura had started. The script was able to connect to Postgres but failed to run any migrations due to Hasura not being up.
2. Ran revert-all-migrations very quickly after Hasura had started.
3. Immediately ran apply-all-migrations.

This run was directly after spinning up a fresh database.

[postgres_logs.txt](https://github.com/NASA-AMMOS/aerie/files/11152560/postgres_logs.txt)
[aerie_db_migration_output.txt](https://github.com/NASA-AMMOS/aerie/files/11152600/aerie_db_migration_output.txt)
[hasura_logs.txt](https://github.com/NASA-AMMOS/aerie/files/11152804/hasura_logs.txt)

**Comment by achong1024** [comment]
Reproduced the error when running 
docker-compose up --scale merlin_worker=5 --scale scheduler_worker=1 -d
![image](https://github.com/NASA-AMMOS/aerie/assets/130383906/981b7ce3-92a2-4890-aaa1-cd4d78140d70)

and try to reduce the number of worker to see if it will fix the error, and it did, if I only have 3 workers
docker-compose up --scale merlin_worker=3 --scale scheduler_worker=1 -d
![image](https://github.com/NASA-AMMOS/aerie/assets/130383906/115c925a-4a2a-45e0-8460-8ec2c5815ef8)

**Comment by Mythicaeda** [comment]
@achong1024, do any of the merlin containers have a connection exception in their logs when this error occurs in postgres?

**Comment by mattdailis** [comment]
We've identified that every Java service opens up 10 connections to postgres and keeps them open continuously. This is the default behavior of [HikariCP](https://github.com/brettwooldridge/HikariCP).

This is reasonable behavior for the "servers", which need to multiplex concurrent HTTP requests. The simulation and scheduler workers, however, leave most of these connections idle, so we believe we can trim down the number of connections that those keep open. This should help create a little more headroom for deploying a larger number of workers.

This addresses Alvin's issue directly, but it appears that that issue is distinct from the one brought up by Parker and Carter. @parkerabercrombie @cartermak, have you continued to run into this issue periodically?

**Comment by cartermak** [comment]
It's been a while since I've seen this issue, although I haven't pushed any instances too hard recently.
