### ISSUE TITLE
Add GitHub issue template for bugs, features, etc.

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#652]
Also see https://github.com/NASA-AMMOS/aerie/issues/673

**Comment by riverma** [comment]
Thanks @camargo. Thoughts on the templates mentioned in #673? Happy to formulate a pull request to close out this ticket.

**Comment by Twisol** [comment]
@riverma, we currently have a PR template (though no issue template) that seems to have served us well so far. I'd be curious to hear your thoughts on it, as someone who's probably had reason to think about these things more often.

https://github.com/NASA-AMMOS/aerie/blob/develop/.github/pull_request_template.md

By the way, your link to your [new feature](https://github.com/nasa-ammos/slim/blob/main/documentation/starter-kits/ISSUE_TEMPLATES/github/new_feature.yml) template seems to be broken.

**Comment by camargo** [comment]
Hey yeah! An issue template for bugs, features, and general issues would be great. PRs welcomed. I'd also like a link to our public Slack as well (see how [this repo does it](https://github.com/sveltejs/kit/issues/new/choose)).

Also curious to hear how you would improve our existing PR template.

**Comment by riverma** [comment]
> @riverma, we currently have a PR template (though no issue template) that seems to have served us well so far. I'd be curious to hear your thoughts on it, as someone who's probably had reason to think about these things more often.
> https://github.com/NASA-AMMOS/aerie/blob/develop/.github/pull_request_template.md

@Twisol @camargo  - that PR template looks great! I hadn't thought about a documentation section - that's a good tip. I think the only thing I'd add is perhaps some examples for the various sections, so that people filling out the template have some sample formatting to pre-use. Our [PR template](https://github.com/nasa-ammos/slim/blob/main/documentation/starter-kits/ISSUE_TEMPLATES/github/PULL_REQUEST_TEMPLATE.md) has some examples on that approach. Additionally, maybe a section header for the first three bullet points just for reading purposes. 

> By the way, your link to your [new feature](https://github.com/nasa-ammos/slim/blob/main/documentation/starter-kits/ISSUE_TEMPLATES/github/new_feature.yml) template seems to be broken.

Good eye! [Here's the link](https://github.com/NASA-AMMOS/slim/blob/main/documentation/starter-kits/ISSUE_TEMPLATES/github/feature_request.yml) to the template. 

> Hey yeah! An issue template for bugs, features, and general issues would be great. PRs welcomed. I'd also like a link to our public Slack as well (see how [this repo does it](https://github.com/sveltejs/kit/issues/new/choose)).

Sure! I can propose PRs for bugs and new features. I'm curious what you all would place in a general issue ticket template. The link to public Slack is pretty slick. Perhaps I can add a PR for the bug and new feature templates that you all can augment with a general issue ticket template + a chat ticket template? After that, would you all be interested in contributing the new general ticket template and the chat ticket template back to SLIM? We could feature it [here](https://nasa-ammos.github.io/slim/documentation/starter-kits/#github-issues-forms) so that other projects can benefit from your approach and suggestions!
