### ISSUE TITLE
Include more information with simulation error messages

### ISSUE THREAD

**Issue by parkerabercrombie** [NASA-AMMOS/aerie#659]
When a simulation fails, it would be really helpful to include the sim time at which the error occurred in the error message that displays in the error console, as well as the name and ID of the activity that threw the error. This would make it _much_ easier to track down issues in the simulation.

```[tasklist]
### Tasks
- [x] Display simulation time at which the error occurred
- [x] Display id of activity that threw the error, if the error was thrown by an activity
```

**Comment by dandelany** [comment]
This came up in discussions yesterday & today with @joswig as something we'd like to improve before the clipper launch release, so I'm going to add the "clipper-launch" label to this & prioritize it. To clarify:

* The main outstanding requirement is: When simulation fails due to an error, the returned error message should include the **activity name** and **ID** of all current "in progress" activities, as well as any additional useful context information that would help debug.
  - Per @mattdailis ^this may be difficult for child activities, and we may only be able to return the name/ID of the **parent** activity, but this should be investigated. Not a blocker - even having parent ID would be an improvement.
* We have also discussed implementing a few other features that would improve this, but are out of scope of this ticket & will be tracked separately:
  - @mattdailis has done some work on a UI for viewing events sent by the server during sim, which would help with debugging - currently a draft but will be PR'ed when ready.
  - It should be possible to display a failed simulation on the timeline as a "partial" sim, ideally displaying the activities which were generated up until the point of the error, and a vertical guideline showing the time at which the error occurred. Will open a separate ticket for this.

**Comment by dandelany** [comment]
Sending to @mattdailis for scoping exactly what the message should contain...

**Comment by mattdailis** [comment]
Slightly workshopping the bullet point above:
> The main outstanding requirement is: When simulation fails due to an error, the returned error message should include the activity name and ID of all current "in progress" activities, as well as any additional useful context information that would help debug. 

I would suggest - When an exception is thrown in a task, identify the directive id that resulted in that task being spawned (i.e. walk the `taskParent` tree up to the directive), and include that information in the simulation exception.

As a starting point - `stepTaskHelper` can catch exceptions from the task's `step` method, and wrap those exceptions in a new exception type that includes the directive id (if one exists), or, if it doesn't, indicates that this is a daemon task.

This design may be impacted by #1174 , which removes the `taskParent` map 🤔 We may need to brainstorm ways to do this bookkeeping in that scenario.
