### ISSUE TITLE
Try to reduce the total number of simulations the scheduler does

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#675]
Do a pass over the scheduling engine to make sure we are not doing any simulation unless absolutely necessary.

**Comment by adrienmaillard** [comment]
Listing some ideas:
- Rootfinding could use one `SimulationFacade` per run as it will always reset. We could probably save them somewhere and if the solution found is finally inserted in the plan, go back from this saved facade
- Loading initial simulation results from DB 
- Caching simulation results during a run. Do not save only the "last" simulation results but others too. querying a simulation result should always include a `Plan` argument and a time domain to see if we can find previous simulation results that would fit the query.

**Comment by mattdailis** [comment]
> simulation result should always include a `Plan` argument and a time domain to see if we can find previous simulation results that would fit the query.

A few weeks ago, I did some experimentation for having the scheduler's simulation facade present a "stateless" interface - i.e. it would always take the full plan, and it would detect changes and decide whether it needs to resume or not. I'm not sure if it will be useful, but I pushed the branch just so that it's available:
https://github.com/NASA-AMMOS/aerie/compare/prototype/scheduler-simulation-accept-whole-plan

**Comment by adrienmaillard** [comment]
Yeah, I think that this is the behavior I originally intended but then I thought we could give more control to the scheduler. But so far, we haven't been able to use this control. 

What I am going so far for another PR is close to your idea. The facade being stateless with regard to results but having a object that stores all the simulation results, indexed by plan. And then in a quite similar way as you, the caller passes the plan and an end time and we first try to look into the cache for results that would work. If not, we simulate.

**Comment by adrienmaillard** [comment]
The problem we will face is always the same, too much freedom :-) Let me take an example: the value of the parameter of an activity can now be whatever expression you want. So maybe it is the value of a resource at the end of the planning horizon. And we don't know what it is before we instantiate it because we do not have this notion of temporal dependency/temporal doman. Resource("...").valueAt(t) has a temporal dependency on time t, it is undefined outside of t by definition.  So it means that whatever I do, when I want to instantiate an activity, I have to get the simulation results for the whole plan. That forces us to resimulate a lot.

**Comment by adrienmaillard** [comment]
Another example, the value of an activity parameter can be the parameter of an anchor activity. This value will not be known before the anchor activity has been determined by the Goal. Let's say that by default, the temporal domain of the aggregation of activity parameters would be the OR expression of domains of their sub-expressions. The relative parameter would have a domain equal to the total horizon UNTIL we know what anchor activity it is going to be. We would need to "replace" the parameter expression by a fixed expression and then this would modify the "temporal" domain of the activity creation.

**Comment by adrienmaillard** [comment]
I am tagging @JoelCourtney here in case this is interesting to him.

**Comment by camargo** [comment]
@adrienmaillard is going to make follow up tickets from this
