### ISSUE TITLE
Usability testing for new timeline designs

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#740]

**Comment by lklyne** [comment]
Shared this out during the UI working group on 3/29/23. 

[#536 Toggle activity directives](https://github.com/NASA-AMMOS/aerie-ui/issues/536) Seems like a good one to prioritize since it seems straightforward and will provide a lot of value cleaning up the timeline

[#825](https://github.com/NASA-AMMOS/aerie/issues/823) [#824](https://github.com/NASA-AMMOS/aerie-ui/issues/835) [#825](https://github.com/NASA-AMMOS/aerie/issues/825) are related to subsystem grouping and color coding. Most users care about activities in the context of the subsystem. If AERIE had context about these subsystems, we could group activities and have quick filters for the timeline, the activity dictionary, and create a universal starting color coding for readability. 

Quick slide summarizing findings:
https://docs.google.com/presentation/d/1cIoX2fhNV_cK-Ccxe5iFsbiByb9-GP6ZBIL-m7OHNlg/edit?usp=sharing

Full notes here:
https://wiki.jpl.nasa.gov/pages/viewpage.action?spaceKey=jeowiki&title=Timeline+Legibility+in+Aerie
