### ISSUE TITLE
Enhanced tracking capability for spawned processes

### ISSUE THREAD

**Issue by bashbash** [NASA-AMMOS/aerie#800]
anselr
https://jira.jpl.nasa.gov/browse/AERIEQS-224
Moderate
Rather simply returning a string with a process ID, consider implementing a dedicated class for spawned processes that gives more insight into the spawned process. Ideally this could be done in such a way that if multiple processes are spawned at once (in a loop or in a stream or via custom machinery), adapters can specify to proceed based on various completion statuses, e.g. continue once one process has completed, after n have completed, or after all processes have completed.

**Comment by mattdailis** [comment]
Since this ticket was created, Aerie has reworked some of its spawn/call machinery - in particular `call` is now defined as a primitive, rather than as the composition of `waitFor` with `spawn`.

> or after all processes have completed.

The recommended pattern for waiting for multiple spawned processes to complete is to spawn all of them from an anonymous subtask, which itself is created using `call`.
```java
call(() -> {
  spawn(...);
  spawn(...);
  spawn(...);
});
```

More involved patterns regarding waiting for N spawned subtasks to complete are not currently planned. With current functionality, this will need to be done with an accumulator cell that each of the subtasks increments, while the parent task waits for a condition.

> Note for the future: dynamically allocated cells could provide a better scoped communication mechanism between parent and child tasks. e.g.:
> ```java
> Cell accumulator = allocate();
> spawn(() -> {
>   ...
>   accumulator.increment();
> })
> spawn(() -> {
>   ...
>   accumulator.increment();
> })
> spawn(() -> {
>   ...
>   accumulator.increment();
> })
> waitUntil(accumulator.isGreaterThan(2))
> ```
