### ISSUE TITLE
Add default roles and permissions to Hasura

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#861]
Requires https://github.com/NASA-AMMOS/aerie/issues/848 to be complete.

This task is to include the default roles and permissions in the Hasrua metadata. See [this document](https://docs.google.com/document/d/1sCIH2AhNDf6LXsSr6il44l_E4QFk3-ykH5SRPqGbdlw/edit) for specifics.

**Comment by Mythicaeda** [comment]
Complication: It is currently [not possible to do cross-db authentication in Hasura](https://github.com/hasura/graphql-engine/issues/8679). 

Currently, I will be skipping the cross-db auth requested on the Scheduler (ie only plan owners/collaborators can edit a scheduling goal), but we need to follow up with a more permanent solution. For example, @mattdailis has suggested creating our own Java API for scheduler auth.

**Comment by mattdailis** [comment]
After some searching, I found where the Hasura docs call this use case out explicitly:

> When this user information is not available in the database that Hasura is configured to use, session variables on the request are the only way to pass this information to a permission rule. In our example, let's assume the mapping of users (members) to organizations may not have been available in the same database.
>
> To convey this information, a session variable, say X-Hasura-Allowed-Organizations can be passed by your authentication service to relay this information

https://hasura.io/docs/latest/auth/authorization/roles-variables/#relationship-information-is-not-available-in-the-same-database

It appears that their recommendation is to have an authentication service (in our case, the gateway, right?) query one database, and provide a list of plan ids to the other via session variables - e.g. `X-Hasura-Owned-Plans` and `X-Hasura-Collaborating-Plans`. 

In our current mental model, are we expecting to use Hasura in webhook mode or JWT mode? Are they mutually exclusive? I'm still wrapping my head around this aspect.

**Comment by camargo** [comment]
@mattdailis Hasrua is in JWT mode for authentication. Yes they are mutually exclusive.

For authorization yeah it looks like we can set additional session headers in the gateway! That can probably be added as part of https://github.com/NASA-AMMOS/aerie/issues/862.

**Comment by Mythicaeda** [comment]
> In our current mental model, are we expecting to use Hasura in webhook mode or JWT mode? 

Our Hasura is in JWT mode.

> Are they mutually exclusive?

Based on [this issue](https://github.com/hasura/graphql-engine/issues/6514) and the wording of [this tutorial](https://hasura.io/learn/graphql/hasura-auth-slack/choosing-jwt-mode/1-choosing-auth-mode/), yes.

> It appears that their recommendation is to have an authentication service (in our case, the gateway, right?) query one database, and provide a list of plan ids to the other via session variables - e.g. X-Hasura-Owned-Plans and X-Hasura-Collaborating-Plans.

Not against this, but would like to go over our current system and what would need to change. Currently, a user signs into the Gateway and is provided a JWT. They then use this JWT to interact with Aerie, without needing to authenticate against the Gateway again for the duration of the session. Given that `owned-plans` and `collaborating-plans` are expected to be decently dynamic--ie, a user can, at any time, make a new plan, which would change the value of `owned-plans`--in order to implement this, we would need:
-  the Gateway to regenerate the JWT either regularly or on some sort of event trigger (without changing the remaining session duration)
-  pass that to the UI 
- notify or pass that to API users

While the first two seem relatively straightforward, I'm not sure how to resolve the third step.
