### ISSUE TITLE
Sort expansion sequence if all commands are epoch relative

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#865]

**Comment by biqua** [comment]
@camargo @cohansen My understanding is that not only epoch commands, but also absolutely timed commands should be sorted (which is the majority of our use cases). See #759 (but in Jira because expanded commands should *not* be in the public github). Are absolute timed commands included in another ticket?

**Comment by cohansen** [comment]
> @camargo @cohansen My understanding is that not only epoch commands, but also absolutely timed commands should be sorted (which is the majority of our use cases). See #759 (but in Jira because expanded commands should _not_ be in the public github). Are absolute timed commands included in another ticket?

Yep, absolute and relative commands are already being sorted per this issue and associated PR: #828.

**Comment by biqua** [comment]
> > @camargo @cohansen My understanding is that not only epoch commands, but also absolutely timed commands should be sorted (which is the majority of our use cases). See #759 (but in Jira because expanded commands should _not_ be in the public github). Are absolute timed commands included in another ticket?
> 
> Yep, absolute and relative commands are already being sorted per this issue and associated PR: #828.

Ah-ha! Great, thank you. :-)

**Comment by camargo** [comment]
Closing. This will not apply an expanded sequence for multiple activities.
