### ISSUE TITLE
Coexistence `foreach` doesn't completely filter Activity Directives when given an ActivityExpression with parameters

### ISSUE THREAD

**Issue by Mythicaeda** [NASA-AMMOS/aerie#925]
If the `forEach` specifies an ActivityType with a certain subset of parameters, we disregard the parameters part of the filter and only filter on ActivityType

Example Goal:
```typescript
export default () =>
  Goal.CoexistenceGoal({
    forEach: ActivityExpression.build(ActivityTypes.PeelBanana, { peelDirection: 'fromStem' }),
    activityTemplate: ActivityTemplates.GrowBanana({
      quantity: 1,
      growingDuration: Temporal.Duration.from({ hours: 1 }),
    }),
    startsWithin: TimingConstraint.range(WindowProperty.END, Operator.PLUS, Temporal.Duration.from({ minutes: 5 }))
  });
```

Example Plan:
Bananation Plan with 2 `PeelBanana` Activities with different start times. One has `peelDirection: fromStem`, the other had `peelDirection: fromTip`

Expected Output:
One `GrowBanana` is placed 5 minutes after the `PeelBanana` with `peelDirection: fromStem`

Actual Output:
Two `GrowBanana`s are placed, one after each `PeelBanana`.

**Comment by mattdailis** [comment]
For context, #847 expanded the capability of ActivityExpression to allow a subset of parameters to be specified. It added this capability to the `activityFinder` parameter, but did not change the `forEach` parameter of CoexistenceGoal.

The `forEach` parameter of CoexistenceGoal uses an `Expression<Spans>`, while `activityFinder` uses the scheduler's `ActivityExpression` class.

Our earlier attempts to unify them were stymied because we had yet to introduce the concept of "span" to constraints - the optimist in me says that it should be possible to subsume ActivityExpression completely, replacing it with `Expression<Spans>`. Any thoughts on this, @JoelCourtney?

**Comment by JoelCourtney** [comment]
@mattdailis I don't know when this happened, but this is already the case. The ActivityExpression get converted to `Expression<Spans>` in `GoalBuilder.spansOfConstraintExpression`. As part of my implementation for this issue I've modified `ForEachActivitySpans` (which is the constraints AST node that does the conversion) to take an arbitrary activity predicate to do its filtering.

**Comment by mattdailis** [comment]
> @mattdailis I don't know when this happened, but this is already the case. The ActivityExpression get converted to `Expression<Spans>` in `GoalBuilder.spansOfConstraintExpression`. As part of my implementation for this issue I've modified `ForEachActivitySpans` (which is the constraints AST node that does the conversion) to take an arbitrary activity predicate to do its filtering.

Pulling up the implementation of `spansOfConstraintExpression` now, I think it might just be keying off the type, and ignoring the arguments - does that sound accurate?
