### ISSUE TITLE
Add additional database tables for tags

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#928]
Based on the [tags design](https://github.com/NASA-AMMOS/aerie-ui/issues/604), we will probably need to add one or more additional tag tables to store global tags.

**Comment by Mythicaeda** [comment]
Implementation Details from the WG:
- Add table `tags`, scope: deployment, columns: `name`, `color`, `owner` (additional metadata?)
- Figure out how to sync tags across the DBs (Hasura foreign DB relationships?)
- Plans need tags
- Permissions on tags: Any user can create, tag owner can update/delete
- Tags for various items (ie `activity_directive`s,`plan`s, `scheduling_goal`s), may have to be changed from a list to an association table (a la `preset_to_directive`) in order to enforce the FK relationship between declared tags and applied tags. _This will impact plan merge._
