### ISSUE TITLE
Prototype running Java inside of Monaco Editor 

### ISSUE THREAD

**Issue by camargo** [NASA-AMMOS/aerie#930]
This is to check feasibility of writing Java (e.g. scheduling goals) directly in the browser.

**Comment by camargo** [comment]
I was able to do this using the [java-language-server](https://github.com/georgewfraser/java-language-server) project and [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) library. Still would require a bit of front-end work and infrastructure to fully support. But certainly within reach if we wanted to go this direction.

![screenshot_2023-05-10_at_2 23 08_pm](https://github.com/NASA-AMMOS/aerie/assets/683355/01d0f3c6-09a8-4aab-b293-2459daf02379)

**Comment by parkerabercrombie** [comment]
Good to know that this is possible, but we would probably use a real Java dev environment to write Java rules rather than Monaco.

**Comment by camargo** [comment]
@parkerabercrombie In that case this brings up a broader question of, if we did go with Java-based scheduling goals instead of TypeScript-based, would a web-based editor even be required anymore?

**Comment by parkerabercrombie** [comment]
I thought we were discussing Java-based scheduling _in addition to_ TypeScript-based, not instead of. I don't think a web-based Java editor is required. The TypeScript editor has been useful.

**Comment by mattdailis** [comment]
> I thought we were discussing Java-based scheduling _in addition to_ TypeScript-based, not instead of. I don't think a web-based Java editor is required. The TypeScript editor has been useful.

That's my bad - I should communicate the ongoing discussions out better. Chris's prototype came from a scheduling working group discussion, where a commonly held perception was that if scheduling goals were written in Java instead of TypeScript, the feature would be more maintainable, resulting in an ability to meet user needs more quickly. The purpose here was to show a proof of concept - since a big open question was whether we could provide all of the desired editing features in a browser editor. My takeaway from this prototype is yes, sort of - though I still expect a steep increase in maintenance complexity if we want to continue to do static type checking on mission-model specific values, like resource names.

All of these discussions are at the notional "could we even?" stage now - we would not pull the trigger on such a change without including stakeholders in the discussion.
