### ISSUE TITLE
No Hinting for Immediate Commands

### ISSUE THREAD

**Issue by cartermak** [NASA-AMMOS/aerie#932]
### Checked for duplicates

Yes - I've already checked

### Is this a regression?

No - This is a new bug

### Version

1.6.0

### Describe the bug

Argument hinting doesn't work on immediate commands. This screenshot shows the hinting/autofill options after using `Ctrl + Space` when filling out immediate command arguments; starting to type the argument name doesn't filter down to the allowable value (`echo_string`, here), either.

![image](https://github.com/NASA-AMMOS/aerie/assets/49076171/39e6a9d8-7b44-495d-95a9-8cbc65e15d66)

### Reproduction

- Create/edit a sequence with an `immediate_commands` list defined
- Write the stem of an immediate command that has arguments and type the opening parenthesis and curly brace
- Use the `Ctrl + Space` shortcut
- Observe that the type hinting (which works for commands in `steps`) doesn't work

### System Info

```shell
Firefox 102.11.0esr on MacOS 13.3.1 (a)
```

### Severity

Minor

**Comment by camargo** [comment]
This is a limitation noted in https://github.com/NASA-AMMOS/aerie/pull/827. We could not support typing for these commands since the Seq JSON spec does not specify a type.

This should be obviated by https://github.com/NASA-AMMOS/aerie/issues/877 when we update the Seq JSON spec to use a `realtime_commands` property instead of immediate and hardware. Closing this, please track https://github.com/NASA-AMMOS/aerie/issues/877. Will note this ticket there.

**Comment by cartermak** [comment]
Ah -- thanks @camargo. I'll track that ticket/the SeqJSON schema change for this functionality.
